# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 23:03
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180526_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
    ]
